PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;
CREATE TABLE circo (
id INTEGER PRIMARY KEY AUTOINCREMENT,
nome TEXT NOT NULL,
conta_id INTEGER NOT NULL,
FOREIGN KEY (conta_id) REFERENCES conta(id));
CREATE TABLE conta (
id INTEGER PRIMARY KEY AUTOINCREMENT,
circo_id INTEGER NOT NULL,
FOREIGN KEY (circo_id) REFERENCES circo(id));
CREATE TABLE transacoes (
id INTEGER PRIMARY KEY AUTOINCREMENT,
conta_id INTEGER NOT NULL,
amount REAL NOT NULL,
FOREIGN KEY (conta_id) REFERENCES conta(id));
CREATE TABLE show (
id INTEGER PRIMARY KEY AUTOINCREMENT,
gasto REAL,
ganho REAL,
circo_id INTEGER,
FOREIGN KEY (circo_id) REFERENCES circo(id));
CREATE TABLE animal(
id INTEGER PRIMARY KEY AUTOINCREMENT,
circo_id INTEGER NOT NULL,
custo REAL NOT NULL,
tipo TEXT NOT NULL,
FOREIGN KEY (circo_id) REFERENCES circo(id));
CREATE TABLE funcionario (
id INTEGER PRIMARY KEY AUTOINCREMENT,
nome TEXT NOT NULL,
ocupacao TEXT NOT NULL,
tipo TEXT,
circo_id INTEGER NOT NULL,
FOREIGN KEY (circo_id) REFERENCES circo(id));
CREATE TABLE item (
id INTEGER PRIMARY KEY AUTOINCREMENT,
funcionario_id INTEGER NOT NULL,
tipo TEXT NOT NULL,
custo REAL NOT NULL,
FOREIGN KEY (funcionario_id) REFERENCES funcionario(id));
DELETE FROM sqlite_sequence;
COMMIT;
